name: second-action-with-code
on: workflow_dispatch
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
        working-directory: ./code-for-2nd-action
      - name: Run test
        run: npm test
        working-directory: ./code-for-2nd-action
